name: my_chat
description: Flutter Chat App With Elixir Absinth Graphql Backend

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0
  provider: ^4.0.2

  cupertino_icons: ^0.1.2

# Chat Agora
  firebase_auth: ^0.15.3+1
  cloud_firestore: ^0.13.0+1
  geolocator: ^5.2.0
  latlong: ^0.6.1
  flutter_map: ^0.8.2
  agora_rtc_engine: ^1.0.5
  permission_handler: ^4.2.0+hotfix.2
  flushbar:
  charts_flutter:
  font_awesome_flutter:
  flutter_launcher_icons: ^0.7.4
  sqflite:
  flutter_i18n:
  date_format: ^1.0.8
  flutter_local_notifications:
  path_provider:
  firebase_messaging: ^6.0.9
  fluttertoast: ^3.1.3
  theme_provider: ^0.3.2
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  fluro: ^1.5.1
  logger: ^0.8.3
  app_settings: ^3.0.0+1
  rflutter_alert: ^1.0.3
  showcaseview: ^0.1.5
  after_layout: ^1.0.7+2
  random_string: ^2.0.1
  artemis: ^3.0.0
  graphql_flutter: ^3.0.0
  built_collection: ^4.3.2

  flutter_swiper: ^1.1.6

#  Chat 3
#  flutter_facebook_login: ^1.1.1
#  http: ^0.12.0+2
#  json_annotation: ^2.0.0
  camera: ^0.5.2+1
  photo_view:
  firebase_storage:
  firebase_database: ^3.1.1
  image_picker: ^0.6.3+1
#  cached_network_image:
  intl:
#  shared_preferences:
#  speech_recognition:
#  image:
  onesignal: ^1.1.0
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

#  SnS
  url_launcher: ^5.4.1
  pin_input_text_field: ^3.0.1
  connectivity: ^0.4.6+1
  network_to_file_image: ^2.2.4
  time_formatter: ^1.0.0+5
  palette_generator: ^0.2.0
  web_socket_channel: ^1.1.0
  video_player: ^0.10.5+2
  flutter_downloader: ^1.4.0
#  flutter_exif_rotation: ^0.2.7
  country_code_picker: ^1.2.3
  country_pickers: ^1.1.0
  device_info: ^0.4.1+4
  file_picker: ^1.4.3+2
  video_thumbnail: ^0.2.0
  open_file: ^3.0.1
  flutter_cache_manager: ^1.1.3
  barcode_scan: ^1.0.0
  qr_flutter: ^3.2.0
  pull_to_refresh: ^1.5.8
  contacts_service: ^0.3.10
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.3
  rxdart: ^0.23.1
  google_sign_in: ^4.1.1
  sembast: ^2.1.2+3
  emoji_picker: ^0.1.0

# E2E
  shared_preferences: ^0.5.3+1
  diacritic: ^0.1.1
  sentry: ^2.2.0
  image_cropper: ^1.0.2
  share: ^0.6.1
  scoped_model: ^1.0.1
  local_auth: ^0.6.1
  crypto: ^2.0.6
  encrypt: ^3.0.0
  localstorage: ^3.0.1+4
  mime: ^0.9.6+2
  ntp: ^1.0.3
  launch_review: ^2.0.0
  flutter_secure_storage: ^3.2.1+1
  giphy_client: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.0
  json_serializable: ^3.0.0
  built_value: ^7.0.8
  hive_generator: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/huddleLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - images/
    - assets/images/
    - assets/flags/
    - assets/i18n/

  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
          weight: 400
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
    - family: Baskervville
      fonts:
        - asset: assets/fonts/Baskervville-Regular.ttf
          weight: 400
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
          weight: 400
    - family: Ubunutu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: UbunutuMono
      fonts:
        - asset: assets/fonts/UbuntuMono.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono.ttf
    - family: B612Mono
      fonts:
        - asset: assets/fonts/B612Mono.ttf